// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: lists.proto

package lists

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListUUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ListUUID) Reset() {
	*x = ListUUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lists_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUUID) ProtoMessage() {}

func (x *ListUUID) ProtoReflect() protoreflect.Message {
	mi := &file_lists_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUUID.ProtoReflect.Descriptor instead.
func (*ListUUID) Descriptor() ([]byte, []int) {
	return file_lists_proto_rawDescGZIP(), []int{0}
}

func (x *ListUUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UserWithList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListUUID         string `protobuf:"bytes,1,opt,name=listUUID,proto3" json:"listUUID,omitempty"`
	UserWithListUUID string `protobuf:"bytes,2,opt,name=UserWithListUUID,proto3" json:"UserWithListUUID,omitempty"`
}

func (x *UserWithList) Reset() {
	*x = UserWithList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lists_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserWithList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserWithList) ProtoMessage() {}

func (x *UserWithList) ProtoReflect() protoreflect.Message {
	mi := &file_lists_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserWithList.ProtoReflect.Descriptor instead.
func (*UserWithList) Descriptor() ([]byte, []int) {
	return file_lists_proto_rawDescGZIP(), []int{1}
}

func (x *UserWithList) GetListUUID() string {
	if x != nil {
		return x.ListUUID
	}
	return ""
}

func (x *UserWithList) GetUserWithListUUID() string {
	if x != nil {
		return x.UserWithListUUID
	}
	return ""
}

type UsersUUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UsersUUID) Reset() {
	*x = UsersUUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lists_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersUUID) ProtoMessage() {}

func (x *UsersUUID) ProtoReflect() protoreflect.Message {
	mi := &file_lists_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersUUID.ProtoReflect.Descriptor instead.
func (*UsersUUID) Descriptor() ([]byte, []int) {
	return file_lists_proto_rawDescGZIP(), []int{2}
}

func (x *UsersUUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId string `protobuf:"bytes,2,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
}

func (x *ListName) Reset() {
	*x = ListName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lists_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListName) ProtoMessage() {}

func (x *ListName) ProtoReflect() protoreflect.Message {
	mi := &file_lists_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListName.ProtoReflect.Descriptor instead.
func (*ListName) Descriptor() ([]byte, []int) {
	return file_lists_proto_rawDescGZIP(), []int{3}
}

func (x *ListName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListName) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lists_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lists_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_lists_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListTwit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *ListUUID              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Text     string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Nickname string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *ListTwit) Reset() {
	*x = ListTwit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lists_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTwit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTwit) ProtoMessage() {}

func (x *ListTwit) ProtoReflect() protoreflect.Message {
	mi := &file_lists_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTwit.ProtoReflect.Descriptor instead.
func (*ListTwit) Descriptor() ([]byte, []int) {
	return file_lists_proto_rawDescGZIP(), []int{5}
}

func (x *ListTwit) GetId() *ListUUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListTwit) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *ListTwit) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ListTwit) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

var File_lists_proto protoreflect.FileDescriptor

var file_lists_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x61, 0x69, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x55, 0x55, 0x49, 0x44,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x56, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x57, 0x69,
	0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x55, 0x55,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x55, 0x55,
	0x49, 0x44, 0x12, 0x2a, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x4c, 0x69,
	0x73, 0x74, 0x55, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x55, 0x73,
	0x65, 0x72, 0x57, 0x69, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x55, 0x49, 0x44, 0x22, 0x21,
	0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x73, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x3c, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22,
	0x24, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x77,
	0x69, 0x74, 0x12, 0x1e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x55, 0x55, 0x49, 0x44, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x32, 0xa4, 0x03, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x12, 0x0f,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x55, 0x55, 0x49, 0x44, 0x1a,
	0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x30,
	0x01, 0x12, 0x36, 0x0a, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x13, 0x61, 0x64, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x57, 0x69, 0x74, 0x68,
	0x4c, 0x69, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x18, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x57, 0x69, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0c,
	0x67, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x0e, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x55, 0x55, 0x49, 0x44, 0x1a, 0x12, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3f, 0x0a, 0x1b, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x54, 0x77, 0x69, 0x74,
	0x73, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x55, 0x55, 0x49, 0x44, 0x1a,
	0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x77, 0x69, 0x74, 0x30,
	0x01, 0x12, 0x36, 0x0a, 0x10, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x6c, 0x69, 0x73,
	0x74, 0x55, 0x55, 0x49, 0x44, 0x1a, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x3b,
	0x5f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lists_proto_rawDescOnce sync.Once
	file_lists_proto_rawDescData = file_lists_proto_rawDesc
)

func file_lists_proto_rawDescGZIP() []byte {
	file_lists_proto_rawDescOnce.Do(func() {
		file_lists_proto_rawDescData = protoimpl.X.CompressGZIP(file_lists_proto_rawDescData)
	})
	return file_lists_proto_rawDescData
}

var file_lists_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_lists_proto_goTypes = []interface{}{
	(*ListUUID)(nil),              // 0: main.listUUID
	(*UserWithList)(nil),          // 1: main.UserWithList
	(*UsersUUID)(nil),             // 2: main.UsersUUID
	(*ListName)(nil),              // 3: main.ListName
	(*ListResponse)(nil),          // 4: main.ListResponse
	(*ListTwit)(nil),              // 5: main.ListTwit
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_lists_proto_depIdxs = []int32{
	0, // 0: main.ListTwit.id:type_name -> main.listUUID
	6, // 1: main.ListTwit.date:type_name -> google.protobuf.Timestamp
	2, // 2: main.ListService.getLists:input_type -> main.UsersUUID
	3, // 3: main.ListService.createCustomList:input_type -> main.ListName
	1, // 4: main.ListService.addUserToCustomList:input_type -> main.UserWithList
	1, // 5: main.ListService.removeUserFromCustomList:input_type -> main.UserWithList
	0, // 6: main.ListService.getListUsers:input_type -> main.listUUID
	0, // 7: main.ListService.getUsersTwitsFromCustomList:input_type -> main.listUUID
	0, // 8: main.ListService.deleteCustomList:input_type -> main.listUUID
	3, // 9: main.ListService.getLists:output_type -> main.ListName
	4, // 10: main.ListService.createCustomList:output_type -> main.ListResponse
	4, // 11: main.ListService.addUserToCustomList:output_type -> main.ListResponse
	4, // 12: main.ListService.removeUserFromCustomList:output_type -> main.ListResponse
	4, // 13: main.ListService.getListUsers:output_type -> main.ListResponse
	5, // 14: main.ListService.getUsersTwitsFromCustomList:output_type -> main.ListTwit
	4, // 15: main.ListService.deleteCustomList:output_type -> main.ListResponse
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lists_proto_init() }
func file_lists_proto_init() {
	if File_lists_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lists_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lists_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserWithList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lists_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersUUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lists_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lists_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lists_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTwit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lists_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lists_proto_goTypes,
		DependencyIndexes: file_lists_proto_depIdxs,
		MessageInfos:      file_lists_proto_msgTypes,
	}.Build()
	File_lists_proto = out.File
	file_lists_proto_rawDesc = nil
	file_lists_proto_goTypes = nil
	file_lists_proto_depIdxs = nil
}
