version: '3.7'
services:
  mongo:
    image: 'mongo:4.2.14-bionic'
    container_name: mongo
    ports:
    - '27017:27017'
    volumes:
    - ./mongodata:/data/db
    restart: always
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
    - '8081:8081'
    restart: always