// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package reactions

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReactionServiceClient is the client API for ReactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReactionServiceClient interface {
	GetTwitReactions(ctx context.Context, in *ReactionUUID, opts ...grpc.CallOption) (*ActionResult, error)
	ReactToTwit(ctx context.Context, in *UsersAction, opts ...grpc.CallOption) (*ResponseReaction, error)
	UnreactToTwit(ctx context.Context, in *UsersAction, opts ...grpc.CallOption) (*ResponseReaction, error)
}

type reactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReactionServiceClient(cc grpc.ClientConnInterface) ReactionServiceClient {
	return &reactionServiceClient{cc}
}

func (c *reactionServiceClient) GetTwitReactions(ctx context.Context, in *ReactionUUID, opts ...grpc.CallOption) (*ActionResult, error) {
	out := new(ActionResult)
	err := c.cc.Invoke(ctx, "/main.ReactionService/getTwitReactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reactionServiceClient) ReactToTwit(ctx context.Context, in *UsersAction, opts ...grpc.CallOption) (*ResponseReaction, error) {
	out := new(ResponseReaction)
	err := c.cc.Invoke(ctx, "/main.ReactionService/reactToTwit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reactionServiceClient) UnreactToTwit(ctx context.Context, in *UsersAction, opts ...grpc.CallOption) (*ResponseReaction, error) {
	out := new(ResponseReaction)
	err := c.cc.Invoke(ctx, "/main.ReactionService/unreactToTwit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReactionServiceServer is the server API for ReactionService service.
// All implementations must embed UnimplementedReactionServiceServer
// for forward compatibility
type ReactionServiceServer interface {
	GetTwitReactions(context.Context, *ReactionUUID) (*ActionResult, error)
	ReactToTwit(context.Context, *UsersAction) (*ResponseReaction, error)
	UnreactToTwit(context.Context, *UsersAction) (*ResponseReaction, error)
	mustEmbedUnimplementedReactionServiceServer()
}

// UnimplementedReactionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReactionServiceServer struct {
}

func (UnimplementedReactionServiceServer) GetTwitReactions(context.Context, *ReactionUUID) (*ActionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTwitReactions not implemented")
}
func (UnimplementedReactionServiceServer) ReactToTwit(context.Context, *UsersAction) (*ResponseReaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReactToTwit not implemented")
}
func (UnimplementedReactionServiceServer) UnreactToTwit(context.Context, *UsersAction) (*ResponseReaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnreactToTwit not implemented")
}
func (UnimplementedReactionServiceServer) mustEmbedUnimplementedReactionServiceServer() {}

// UnsafeReactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReactionServiceServer will
// result in compilation errors.
type UnsafeReactionServiceServer interface {
	mustEmbedUnimplementedReactionServiceServer()
}

func RegisterReactionServiceServer(s grpc.ServiceRegistrar, srv ReactionServiceServer) {
	s.RegisterService(&ReactionService_ServiceDesc, srv)
}

func _ReactionService_GetTwitReactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactionUUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).GetTwitReactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ReactionService/getTwitReactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).GetTwitReactions(ctx, req.(*ReactionUUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReactionService_ReactToTwit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).ReactToTwit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ReactionService/reactToTwit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).ReactToTwit(ctx, req.(*UsersAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReactionService_UnreactToTwit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).UnreactToTwit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ReactionService/unreactToTwit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).UnreactToTwit(ctx, req.(*UsersAction))
	}
	return interceptor(ctx, in, info, handler)
}

// ReactionService_ServiceDesc is the grpc.ServiceDesc for ReactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.ReactionService",
	HandlerType: (*ReactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getTwitReactions",
			Handler:    _ReactionService_GetTwitReactions_Handler,
		},
		{
			MethodName: "reactToTwit",
			Handler:    _ReactionService_ReactToTwit_Handler,
		},
		{
			MethodName: "unreactToTwit",
			Handler:    _ReactionService_UnreactToTwit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reactions.proto",
}
