// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: reactions.proto

package reactions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TwitId        *ReactionUUID `protobuf:"bytes,1,opt,name=twitId,proto3" json:"twitId,omitempty"`
	LikeCounter   int32         `protobuf:"varint,2,opt,name=likeCounter,proto3" json:"likeCounter,omitempty"`
	RetwitCounter int32         `protobuf:"varint,3,opt,name=retwitCounter,proto3" json:"retwitCounter,omitempty"`
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_reactions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_reactions_proto_rawDescGZIP(), []int{0}
}

func (x *ActionResult) GetTwitId() *ReactionUUID {
	if x != nil {
		return x.TwitId
	}
	return nil
}

func (x *ActionResult) GetLikeCounter() int32 {
	if x != nil {
		return x.LikeCounter
	}
	return 0
}

func (x *ActionResult) GetRetwitCounter() int32 {
	if x != nil {
		return x.RetwitCounter
	}
	return 0
}

type UsersAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TwitId *ReactionUUID `protobuf:"bytes,1,opt,name=twitId,proto3" json:"twitId,omitempty"`
	Action string        `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	User   string        `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UsersAction) Reset() {
	*x = UsersAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersAction) ProtoMessage() {}

func (x *UsersAction) ProtoReflect() protoreflect.Message {
	mi := &file_reactions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersAction.ProtoReflect.Descriptor instead.
func (*UsersAction) Descriptor() ([]byte, []int) {
	return file_reactions_proto_rawDescGZIP(), []int{1}
}

func (x *UsersAction) GetTwitId() *ReactionUUID {
	if x != nil {
		return x.TwitId
	}
	return nil
}

func (x *UsersAction) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *UsersAction) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ResponseReaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ResponseReaction) Reset() {
	*x = ResponseReaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseReaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseReaction) ProtoMessage() {}

func (x *ResponseReaction) ProtoReflect() protoreflect.Message {
	mi := &file_reactions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseReaction.ProtoReflect.Descriptor instead.
func (*ResponseReaction) Descriptor() ([]byte, []int) {
	return file_reactions_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseReaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ReactionUUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReactionUUID) Reset() {
	*x = ReactionUUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reactions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReactionUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionUUID) ProtoMessage() {}

func (x *ReactionUUID) ProtoReflect() protoreflect.Message {
	mi := &file_reactions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionUUID.ProtoReflect.Descriptor instead.
func (*ReactionUUID) Descriptor() ([]byte, []int) {
	return file_reactions_proto_rawDescGZIP(), []int{3}
}

func (x *ReactionUUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_reactions_proto protoreflect.FileDescriptor

var file_reactions_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x82, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x74, 0x77, 0x69, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x06, 0x74, 0x77,
	0x69, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6c, 0x69, 0x6b, 0x65, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x74, 0x77, 0x69, 0x74,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x72,
	0x65, 0x74, 0x77, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x65, 0x0a, 0x0b,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x06, 0x74,
	0x77, 0x69, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x55, 0x49, 0x44, 0x52,
	0x06, 0x74, 0x77, 0x69, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x24, 0x0a,
	0x0c, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x32, 0xc3, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x54, 0x77,
	0x69, 0x74, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x55, 0x49, 0x44, 0x1a,
	0x12, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x38, 0x0a, 0x0b, 0x72, 0x65, 0x61, 0x63, 0x74, 0x54, 0x6f, 0x54, 0x77,
	0x69, 0x74, 0x12, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a,
	0x0d, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x63, 0x74, 0x54, 0x6f, 0x54, 0x77, 0x69, 0x74, 0x12, 0x11,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x3b,
	0x5f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reactions_proto_rawDescOnce sync.Once
	file_reactions_proto_rawDescData = file_reactions_proto_rawDesc
)

func file_reactions_proto_rawDescGZIP() []byte {
	file_reactions_proto_rawDescOnce.Do(func() {
		file_reactions_proto_rawDescData = protoimpl.X.CompressGZIP(file_reactions_proto_rawDescData)
	})
	return file_reactions_proto_rawDescData
}

var file_reactions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_reactions_proto_goTypes = []interface{}{
	(*ActionResult)(nil),     // 0: main.ActionResult
	(*UsersAction)(nil),      // 1: main.UsersAction
	(*ResponseReaction)(nil), // 2: main.ResponseReaction
	(*ReactionUUID)(nil),     // 3: main.reactionUUID
}
var file_reactions_proto_depIdxs = []int32{
	3, // 0: main.ActionResult.twitId:type_name -> main.reactionUUID
	3, // 1: main.UsersAction.twitId:type_name -> main.reactionUUID
	3, // 2: main.ReactionService.getTwitReactions:input_type -> main.reactionUUID
	1, // 3: main.ReactionService.reactToTwit:input_type -> main.UsersAction
	1, // 4: main.ReactionService.unreactToTwit:input_type -> main.UsersAction
	0, // 5: main.ReactionService.getTwitReactions:output_type -> main.ActionResult
	2, // 6: main.ReactionService.reactToTwit:output_type -> main.ResponseReaction
	2, // 7: main.ReactionService.unreactToTwit:output_type -> main.ResponseReaction
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reactions_proto_init() }
func file_reactions_proto_init() {
	if File_reactions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reactions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseReaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reactions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReactionUUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reactions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reactions_proto_goTypes,
		DependencyIndexes: file_reactions_proto_depIdxs,
		MessageInfos:      file_reactions_proto_msgTypes,
	}.Build()
	File_reactions_proto = out.File
	file_reactions_proto_rawDesc = nil
	file_reactions_proto_goTypes = nil
	file_reactions_proto_depIdxs = nil
}
